import { useState } from "react";
import { BsStars } from "react-icons/bs";
import b_image from "../assets/banner.png";

const Tabs = () => {
  const [activeTab, setActiveTab] = useState("Tab1");

  const handleTabClick = (tab) => {
    setActiveTab(tab);
  };

  return (
    <div className="p-4">
      <div className="flex justify-center gap-3">
        <button
          className={`px-6 py-4 focus:outline-none rounded-md ${
            activeTab === "Tab1"
              ? "text-gray-100 bg-primary-color"
              : "text-gray-500 bg-black"
          }`}
          onClick={() => handleTabClick("Tab1")}
        >
          AI Video Subtitles
        </button>
        <button
          className={`px-6 py-4 focus:outline-none rounded-md ${
            activeTab === "Tab2"
              ? "text-gray-100 bg-primary-color"
              : "text-gray-500 bg-black"
          }`}
          onClick={() => handleTabClick("Tab2")}
        >
          YouTube Translation
        </button>
        <button
          className={`px-6 py-4 focus:outline-none rounded-md ${
            activeTab === "Tab3"
              ? "text-gray-100 bg-primary-color"
              : "text-gray-500 bg-black"
          }`}
          onClick={() => handleTabClick("Tab3")}
        >
          Images Generation
        </button>
      </div>

      <div className="mt-20">
        {activeTab === "Tab1" && (
          <div className="space-y-5 w-1/2 h-96">
            <p className="text-3xl font-bold text-gray-100">
              Transformative AI Elevating Videos with Automated Subtitling
            </p>

            <p className="text-gray-400">
              Step into the realm of cutting-edge video enhancement with our
              AI-driven subtitle tool, revolutionizing content accessibility.
            </p>

            <div className="flex items-center gap-3 ">
              <p className="text-primary-color text-3xl">
                <BsStars />
              </p>
              <p className="text-gray-100">
                Empower your content with accurate and timely subtitles,
                effortlessly generated by advanced AI algorithms.
              </p>
            </div>
            <div className="flex items-center gap-3 ">
              <p className="text-primary-color text-3xl">
                <BsStars />
              </p>
              <p className="text-gray-100">
                Enhance viewer retention and comprehension by providing
                subtitles in multiple languages, facilitated by automated
                translation.
              </p>
            </div>
          </div>
        )}
        {activeTab === "Tab2" && (
          <div className="w-1/2 h-96 text-gray-100">No Data</div>
        )}
        {activeTab === "Tab3" && (
          <div className="w-1/2 h-96 text-gray-100">No Data</div>
        )}
        <div className="relative">
          <img
            className="w-1/2 absolute bottom-0 right-0"
            src={b_image}
            alt=""
          />
        </div>
      </div>
    </div>
  );
};

export default Tabs;
